### ISSUE TITLE
Tracker issue for Sprint 1

### ISSUE THREAD

**Issue by rfairley** [zzlyn/ConsensusVisualization#5]
For overall milestone: https://github.com/zzlyn/ConsensusVisualization/milestone/1

- [x] Node skeleton class (#6)
- [x] Message skeleton class (#7)
- [x] Draw nodes, log (#8)
- [x] Draw message (#9)
- [x] Add basic node attributes (leader, follower), draw to distinguish them (e.g. different color) (#10 )
- [x] Send message function for the node class (which will be a common method for the 3 protocols), which will cause the sent value to show up in the receiver node's log (#11)
